USE MASTER 
GO

-- Tạo database
CREATE DATABASE QuanLyLopHocDB
GO

USE QuanLyLopHocDB
GO

-- Bảng GIAOVIEN
CREATE TABLE GIAOVIEN (
    MaGV NVARCHAR(20) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    SoDienThoai NVARCHAR(20),
    Email NVARCHAR(100),
    CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MaGV),
    CONSTRAINT UQ_EMAIL_GIAOVIEN UNIQUE (Email)
);
GO

-- Bảng MONHOC
CREATE TABLE MONHOC (
    MaMon NVARCHAR(20) NOT NULL,
    TenMon NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_MONHOC PRIMARY KEY (MaMon)
);
GO

-- Bảng LOP
CREATE TABLE LOP (
    MaLop NVARCHAR(20) NOT NULL,
    TenLop NVARCHAR(50) NOT NULL,
    NamHoc INT NOT NULL,
    MaGVCN NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_LOP PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MaGVCN) REFERENCES GIAOVIEN(MaGV)
);
GO

-- Bảng HOCSINH
CREATE TABLE HOCSINH (
    MaHS NVARCHAR(20) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    DiaChi NVARCHAR(200),
    MaLop NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_HOCSINH PRIMARY KEY (MaHS),
    CONSTRAINT FK_HOCSINH_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);
GO

-- Bảng DIEM
CREATE TABLE DIEM (
    MaHS NVARCHAR(20),
    MaMon NVARCHAR(20),
    HocKy INT,
    NamHoc INT NOT NULL,
    DiemSo FLOAT,
    CONSTRAINT PK_DIEM PRIMARY KEY (MaHS, MaMon, HocKy, NamHoc),
    CONSTRAINT FK_DIEM_HOCSINH FOREIGN KEY (MaHS) REFERENCES HOCSINH(MaHS),
    CONSTRAINT FK_DIEM_MONHOC FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon),
    CONSTRAINT CHK_HOCKY CHECK (HocKy IN (1, 2)),
    CONSTRAINT CHK_DIEMSO CHECK (DiemSo BETWEEN 0 AND 10)
);
GO

-- Bảng PHANCONG
CREATE TABLE PHANCONG (
    MaGV NVARCHAR(20) NOT NULL,
    MaMon NVARCHAR(20) NOT NULL,
    MaLop NVARCHAR(20) NOT NULL,
    NamHoc INT NOT NULL,
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MaGV, MaMon, MaLop),
    CONSTRAINT FK_PHANCONG_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_PHANCONG_MONHOC FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon),
    CONSTRAINT FK_PHANCONG_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);
GO

-- Bảng LICHDAY
CREATE TABLE LICHDAY (
    MaGV NVARCHAR(20),
    MaLop NVARCHAR(20),
    MaMon NVARCHAR(20),
    NgayTrongTuan NVARCHAR(10) NOT NULL,
    TietBatDau INT,
    SoTiet INT,
    NamHoc INT NOT NULL,
    HocKy INT,
    CONSTRAINT PK_LICHDAY PRIMARY KEY (MaGV, MaMon, MaLop, NgayTrongTuan, TietBatDau),
    CONSTRAINT FK_LICHDAY_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_LICHDAY_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_LICHDAY_MONHOC FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon),
    CONSTRAINT CHK_TIETBATDAU CHECK (TietBatDau > 0),
    CONSTRAINT CHK_SOTIET CHECK (SoTiet > 0),
    CONSTRAINT CHK_HOCKY_LICHDAY CHECK (HocKy IN (1, 2))
);
GO

-- Bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    IDUser INT PRIMARY KEY IDENTITY(1,1), 
    Username VARCHAR(50) NOT NULL, 
    Password VARBINARY(MAX) NOT NULL, 
    DateCreated DATETIME NOT NULL, 
    Level INT,
    MaGV NVARCHAR(20) NOT NULL, 
    CONSTRAINT FK_MAGV_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT UQ_USERNAME UNIQUE (Username),
    CONSTRAINT CHK_LEVEL CHECK( Level IN (0, 1, 2, 3))
);
GO